apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: platbadane-general-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgCY9S6YNLh8ADyJipsW6TN6BSy/jTUMg0C5nj2dQJDKhzQsBbdiUN/K6HFHhHYRWUOZcmZk/oI1c9h+DeEFrDcTBy3sP23om3/7Y9RRFMtFZ3Yxh6dflRCA9Surzis/qjgZ7KHn8NGV/MjMjW3pJxny4uySZbD+TCBxBSo5RzQWvTpX78YxYMDMHJ4iP6z1LmrStZVRNISvvRBFMeN+7IUP6LSMQsrbXWyDfUzfVZdhTfu6rqSWtpdtXCLWdRHaaeSz9q6kxNQ+5ef00OUIrB/hu9DiScaIqGO2vNth0QvD7n9KC1zq6f6yBRpfcD8hK3A+WV2PznYdHYYX+T9X0CBav12IM8q2jgQKO0enbOG576wCbZvYI85LBhqvQJsvVjKLjRH5uKCFk4mmORb1eNp1M/R22ScfSKs8Vl3s4pPN7Cg4iSlSiOFvSphQr6cp0EzHZo8k2Ob6w+H8UsNnIi2JfVcwhjHoaHSwMplwv5mwXpw4zJ3tRa8lXcgURtdxVNXkPxjAyL5oMLK+/surrI6O0HL4FJKzZVixHQKiglUC2AO3YSumqXlngG2Nafz7fgEagFg6HQIxxoi9XY4Iu2uMBscNxAklx3yMijAoP8arM+zlBgt9lOLeBAWtGseDGQsczSQFOX+aLX1aNQEZiEwZ8hfTDv6gPqMAsVRBCmIqsRbb8J8g58i7G0GqZ8FuxQeaqBf4lztPs42hrXVIzchlHLj6wEb33DOod7LIbC6/aNwhqzttBE7VQ+9uMvqGktCcvYlQ3Jipiw==
    STRAPI_PREVIEW_SECRET: AgBTnnPEghbiaX6UxQwPtfqnDwr3q07/lK2MAQNtjpFLWClsDJi50/stA8AvFfRUO7Aj6q652FqetYw6EJsLTiI+wW8/Rg1AcQ9L0zmsSBBI+j7jV+HG29/xAfPKF29b51AyOqKKoSBId7KeYtIIenxuQCVfm2CXP7vWBklwZ/AAgiC0nQFUumz0CDVdxhSe/b/lKJVsPAQxZhH0NLzvrXYE4c++ASwtZTO7PI4kDG5LVuTTtDoFRZIrspkq4YtNQeCCv0dAwY+hAaz68x552tNn4R9FORr8GNSxsMzlZ5ySMlZgKFWTee7wBxoBC8KEbYphloPeonAiEgvl13O5zw/rAhIqxE7dUh/hsYX1ESfUj6qsGusxkpYkTHr7z5kmFQND8gAlhtlxxWQIPNIz1Bv/4HaKW40+IrhNgylv6kCVLTpYOlBqY4lVTOv3khtm0J888S5asgYsZn1vv6Ei19nCsyVFXHrYb89OO8dvEt2oQ7G/UdAS4q+sANIyDDngtK8kjeYmwn8Oj9w1RGCiRQSm5GS11hnXFOX/EtgeYNXOFRB9Y27eJc6bPTOLEqKFYjB4dRAFdiv8/sNw2JJr6NfOGoS20eZuE1tvaQits6qVqi4y1utv+vQ2IKgsm22t5ESLnzPjBpO9S+eppcgGU9FlL6DyEWH9MAqFeqoifjnoawlCc6Z0zHvdkB/rqTriWu+DfnoUrQXiQmyYoHOT23j+JfQoIF6x1XXn4Yj7MF1UCruj/BGuwe8T/YDVE71GTWFc3T6Szc9QYoU=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: platbadane-general-secret
      namespace: standalone

