apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: platbadane-general-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgAJ00NpKUzuF7HmBxxK4tTPTD46y/g/d99hB/K5jZWA+2D7s+5d0LEJ1hnDTFmhaEFwylUNAhaJ3RFGTxK2jGF+Oa97Xit46qqmHTORpoTee5FvUUwwfC5spXF6SKAomAuVSSNmNCPvCGPR6+OMMTuCxXmZDv7ITcK+G30jlD9EZb9R66swhKdWQsdGAh/w/eQmiOXjJhJdBSf5RC8hUP1YxuG5Xvvw034ftsj+xOocpIRdPqxK4SnLrSNKyyEK5gNAVe54Sb3zVFPqY2GfX74shFlyVw3Ma+guArSP7wwuQ1Q2cdrOOtie+W7NhUqxGGgl1YZauIIXkTb84k4luBN4FPD0/Y1mllecTsbmhCoxB0wrLjNprWVqHuSL9VTtynPtgBPO0jfrwxF7T9Gw189HgcSBvIQuX1xwA/YCMQ0FbRPylLstLNzpCC2YwM3T0h9hhM7UygD++wbZnd5N4haXBn9GsYotfI/BoMj6QXtY47NR5THQeX7TvptZyG/7wbyKjLa9eCnnNZzBEXurgzlf9KCp8NiRhow0cs05Nl4bwdyQO4Xgc03n8HAhZLUBSEr2JCPPNhNRAoPWANDQ0vqAfHtgC6emf31d6jmQBrgTcHFj5raOZN9Vf4k/YwylcvaJgqomZMAhOHgTXLdguTP0QXYZQzMYBuTNZ0+Qh+6muBC9HYsp1QL9pF/LwkguzorlG4UdmDh5w60gVrjTYQ/Nb/V5YfgxH42Shu/hEAcADPkPTxxPlD2kie4AAA==
    STRAPI_PREVIEW_SECRET: AgByEyo/daPlAK2/J/yTFjBo55Kg7qRQ12/qtbza1W6RInyTYiL9mc3hAneEDFagxI8DU9hhZ/m77u78A0RGAWF0eVN2e7zJmTPGi8aiGArQTpBwPJHkWAzJo3WVUGnI2GAZ3FVoyAi9hh5388xWWtTq7otKBnZt6kMZcjUVg5qjLNJxGhprqF7aaqzJ/5RRm/jqGR5jv290X9whdrO9XRsamH1nJ5+LR+tCHYpz9fxwx44pudHxr2gK1nypNOYo+ff0W1uGI78fExnOOMeeyrr7yNjB4sOCNm0+xIdywOqXNlQn2iKNIPDyM0ufR8gfaIy74glzyIoKekhxOxm0O0L0M52M6JEMW5eWzEgOMtLlOUDmwjdcLe/F5Ck/JEFeqrFEWYUcSlJwGuPBQq++jzbHF4tpNd5P3TOiC+MP0B47GhrgB86917Q5xbbbIYqP5Cib3FXixZmBMuL3vDXKND317j/5gMSiTQOU/6o67j+pL2e6tqrW3HZcvMjNfYM2E9NSv+MZoISSV2H3rj4w0s8CDpFmXYWoV1kxk48HRWGqXDqFFKgDlHLCqc8R1gWrHbrAUN6CrD462K2OIgzzcSR/osuoQZ2Y27A2vxDVpz7wzF50MqstcwP15Z2/hDv8WxXqXvNu5veiTdd9IVhCUV5LeGT1BqD+tK11FqLa14mTf00QeOddO7jWOGr1FJWVqBBw4E+Rl40FVyICkOdPeRBUPjsZHDZk4LopJEbFfZa9uKS3ot/xW86zDOBFvQs=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: platbadane-general-secret
      namespace: standalone

