apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: platbadane-general-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgCJYMzFnYiPTXND3yRYQ4Lohza40M1Yh54E9VwRCjUEpQrzi1LpIMbV+DS0vdFscL2pjbXv6Vqx6BxO7cyGfxYXH98GULxM3d0js9hImGHOF3gzm27p7hdRxNDoV51wk0Z+N67V2NrAJsxzauSKlMD+frYAOcQql8EXmiHonoW6UJ2Ju9FabVY7bj6aDn6ixoaC5AE5N6vscSFBNE7DnuIXY3MnX+woUopuMfwNVTXU4vmZdCwd51IAvzGyPyo7KxgbXA9PD1pADJWXG6GzdEasvmbp994VdeuLumKAvkyaNc1RXckkzI0CFZc2DQw4PmY7YaCpEWQG5oCOpIsWmFHZs5F/qhPMfPN/0rLxQBm7g3hQCsGkwKSmyciqzRHMc5DCn8YV28VgMMyGnJXKSQgdrt7g8CfXiFTG4zBggvZKwfEHKYIrhqBHbkC2DNMLxBoiegqGKzz7HXbz8sWK5H+5vwj0z5JZHoBbW3ueF+zPL14aowHM8E9J7NNXzlF43uw77LP+Nszfps4E2FZ5kRrCpjZaPhf1UKahLYOht4/P3nby6V0sHNQWMWmijbG7f615a1eHnwfpPBuwVJEz/Bcv0XgJjbDZNqUyW+qeUKD2RO1XHQp9YM6qVXrveWnPfBVhXaV3kEtOVdGAJ6/N7mSilhRac85O8muaB4fecKJo0fTbOe6ePZVShUksjOpfiWZ/FsL0B1z/qzrFvM1zT5A9OBDxbNozBeMJCgjcb6HXQtdAoHPh1BzPyhqfC3SO6ubaxu2qkms=
    STRAPI_PREVIEW_SECRET: AgCdnGL981m4swNyPdA60chZdXKh9GgBFz9dSaa6REr27i3Uxe/KXRtwRrj3p5tBxC88kz2UFBe2az2Bl4Fit1cMTMl4dcgttsQlLzTC4YpQ77qXM+FBBxKEX8ryorepPZfirAcseSkPEgZXz/ltj0DWkJmuGpwA06Kd1oyxRH/D6qF7CFlwfDqYtlH+08YVFSr3u0y2jfU3nL9FSrQJ0kFho1rrph53YbPx+KENQv3QYPmLJj+ROUkXDzw7ksc3AmCHR2W8kS1FLKHRt3P8L4aQu4L+236XrFjDDzKE5kUx1lX2gcP+awbz3Qp6i/9yxvwp2/FOnJklrAbBqvVRvMDQ0LkMEpVbjP+kQ4MUPPKGQnl3S+a6i5vzvC9yQQefIQqy9bb5VIoiuO5n2LCvqPsXvCOXUhvfSiaA6el3bspFqqlc8W8Wni3PJCCcSiAqoy5WZnxpfuvBSL+sG+7Cfo8HQ5wB8FWGRWSVvpqCGGGhA9jzS+fKMatyGbfRtZ6+Hl/ffgo/aSFDlH+/Yc6pYjq+KneebZUsR8qBTP5JwZLT6xhD+8ll5HlfK7UucHUC0CcCqM/6OHLCaVqOlBptnDoSk37fDBovtHdfEiXqClTP6mgEiMfcne9k4m7pn8oPW2Uiu+MuHNZa++lW6APmfJxtQ4gPKddDxy6utsbtM+NKdvg5DYYrnIvmxR0M8sIWa7PXp+fqJK0pSSYUI4m+lb06N4nHgZqrSnNn0/1VDRt4ULYH2+AQLQSm+hZJ16vbjzBC71zdtt8=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: platbadane-general-secret
      namespace: standalone

